apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: choose-cache
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    This task will generate an image tag.
  params:
  - name: os_name
    type: string
    description: the os of the base image to use at final image build
    default: "ubuntu22.04"
  - name: gcc 
    type: string
    description: the version of gcc
    default: "gcc12"
  - name: build_type 
    type: string
    description: the cpp build_type, release or debug
    default: "release"
  - name: runtime_image
    type: string
    default: alpine:latest
    description: the image of this task
  results:
    - name: conan-cache-name
      description: the path of conan on host 
  steps:
  - name: "choose-conan-cache"
    image: $(params.runtime_image)
    script: |
      #!/usr/bin/env sh

      # in order to get a valid name in kubernetes, have to discard dot charactor 
      # "ubuntu20.04" -> "ubuntu2004" 
      # "ubuntu22.04" -> "ubuntu2204" 
      os=$(echo "$(params.os_name)" | tr -d '.' )

      echo -n  "cache-conan-${os}-$(params.gcc)-$(params.build_type)" | tee $(results.conan-cache-name.path)
