apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml
- serviceaccount.yaml

patches:
 - target:
      group: tekton.dev
      version: v1beta1
      kind: Task
      name: release-lock
   path: release-lock-patch.yaml


