apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: milvus-make-with-conan-workspace
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Image Build
    tekton.dev/tags: docker, build-image, push-image, dind
    tekton.dev/displayName: docker-build
    tekton.dev/platforms: "linux/amd64"
spec:
  params:
  - name: milvus-env
    type: string
    description: the image name of milvusdb/milvus-env to use
  - name: additional-make-params 
    type: string
    description: the params for make commands
    default: "use_disk_index=ON"
  - name: build_type
    type: string
    description: debug mode or release mod
    default: "release"
  - name: go-cache-name
    type: string
    default: "go1-21-cache"
  - name: computing_engine
    type: string
    default: "cpu"
    description: to build cpu image or gpu image
  workspaces:
  - name: source
  - name: conan-cache
    mountPath: /root/.conan
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.
  steps:
  - name: make
    image: $(params.milvus-env)
    env:
    - name: CCACHE_COMPILERCHECK
      value: "content"
    - name: CCACHE_COMPRESS
      value: '1'
    - name: CCACHE_COMPRESSLEVEL
      value: '5'
    - name: CCACHE_MAXSIZE
      value: "2G"
    - name: CCACHE_DIR
      value: "/ccache" 
    workingDir: $(workspaces.source.path)
    script: |
      #!/usr/bin/env sh

      params="$(params.additional-make-params)"

      # append
      if [ $(params.build_type) = "debug" ]; then
         params="${params} mode=Debug"
      fi

      install="install"
      # if it is building gpu image
      if [ "$(params.computing_engine)" = "gpu" ]; then
        install="gpu-install"
      fi
      
      cmd="make clean && make ${install} ${params}"

      echo "[make cmd] ${cmd}"

      sh -c "${cmd}"

    volumeMounts:
      - mountPath: /go/pkg/mod
        name: $(params.go-cache-name)
      - mountPath: /ccache
        name: ccache
  volumes:
  - hostPath:
      # conan cache for ubuntu20.04 os, gcc9 compiler and build type is release
      path: /root/cache/go/go1.21/mod
      type: DirectoryOrCreate
    name: go1-21-cache
  - hostPath:
      path: /root/cache/ccache
      type: DirectoryOrCreate
    name: ccache
