apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-build-push
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Image Build
    tekton.dev/tags: image-build
spec:
  description: >-
    This Task builds source into a container image using Moby BuildKit.
  params:
  - name: image_name
    type: string
    description: Reference of the image docker will produce.
  - name: arch
    type: string
    default: "amd64"
  - name: DOCKERFILE
    description: The name of the Dockerfile
    default: "Dockerfile"
  - name: dockerfile_location
    description: The name of the Dockerfile
    default: "."
  - name: BUILDKIT_CLIENT_IMAGE
    default: "docker.io/moby/buildkit:v0.15.0"
  - name: BUILDKIT_DAEMON_ADDRESS
    description: The address of the BuildKit daemon (buildkitd) service
    default: "tcp://buildkitd.buildkit:1234"
  workspaces:
  - name: source
  steps:
  - name: build-and-push
    image: $(params.BUILDKIT_CLIENT_IMAGE)
    workingDir: $(workspaces.source.path)
    command: ["buildctl", "--debug",
              "--addr=$(params.BUILDKIT_DAEMON_ADDRESS)",
              "build",
              "--progress=plain",
              "--frontend=dockerfile.v0",
              "--opt", "filename=$(params.DOCKERFILE)",
              "--opt", "platform=linux/$(params.arch)",
              "--local", "context=.", "--local", "dockerfile=$(params.dockerfile_location)",
              "--output", "type=image,name=$(params.image_name),push=true",
              "--export-cache", "type=inline",
              "--import-cache", "type=registry,ref=$(params.image_name)"]
