apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sync-env-image
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Image Build
    tekton.dev/tags: docker, build-image, push-image, dind
    tekton.dev/displayName: docker-build
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    The task is using a dind sidecar over TCP+TLS.
    This task will build and push an image using docker.
    The task will compile first in the milvusdb/milvus-env container, then
    build image based on the dockerfile.
    This image will be pushed to an image registry.
  params:
  - name: src
    type: string
    description: the image name of milvusdb/milvus-env to use
  - name: dest
    type: string
    description: the image name of milvusdb/milvus-env to use
  - name: image
    type: string
    description: The location of the docker builder image.
    default: regclient/regctl:v0.6.1-alpine
  steps:
  - name: sync
    image: $(params.image)
    script: |
      #!/usr/bin/env sh
      regctl image copy $(params.src) $(params.dest)
